# *********** IICuX fix 09.08.2015 19:24:41 ***************
#obj-$(CONFIG_ARCH_MT8127) += mt8127/
#obj-$(CONFIG_ARCH_MT6572) += mt6572/
#obj-$(CONFIG_ARCH_MT6592) += mt6592/
# *********** IICuX fix 09.08.2015 19:24:41 ***************
obj-$(CONFIG_ARCH_MT6582) += v1/
obj-$(CONFIG_ARCH_MT6735) += v1/
obj-$(CONFIG_ARCH_MT6752) += v1/
obj-$(CONFIG_ARCH_MT6795) += v1/
obj-$(CONFIG_ARCH_MT8163) += v1/
obj-$(CONFIG_ARCH_MT6580) += v1/
