/*
 * Generated by MTK SP Drv_CodeGen Version 03.13.6  for MT6575_NP. Copyright MediaTek Inc. (C) 2013.
 * Mon Aug 10 00:03:48 2015
 * Do Not Modify the File.
 */



#include "pmic_drv.h"




//For PMIC driver use


